version: "3"

services:
  postgres:
    image: postgres:42.7.2
    restart: always
    environment:
      POSTGRES_DB: cloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3101
    ports:
      - "5433:5432"

