version: "3"

services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - '5555:5000'


  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: cloud
      MYSQL_PASSWORD: 1998
      MYSQL_ROOT_PASSWORD: 3101
      MYSQL_USER: user

  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'
