version: "3"

services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - '5555:5000'
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "cloud"
      MYSQL_PASSWORD: "3101"
      MYSQL_ROOT_PASSWORD: "3101"
      MYSQL_USER: "user"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
