version: "3"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: cloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3101
    ports:
      - "5433:5432"
  minio:
    image: bitnami/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER:${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD:${MINIO_SECRET_KEY}


