version: "3"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: cloud
      POSTGRES_USER: cloud_user
      POSTGRES_PASSWORD: cloud_password
    ports:
      - 5432

