spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/cloud
    username: postgres
    password: 3101
  jpa:
    show-sql: true
minio:
  bucket: files-bucket
  url: http://localhost:9000
  accessKey: cloud
  secretKey: 123456789