spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/cloud
    username: postgres
    password: 3101
  jpa:
    show-sql: true
minio:
  bucket: cloudfilestorage
  url: https://play.min.io
  accessKey: cloud
  secretKey: 123456789

